// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CSRPulse.Data.Models
{
    public partial class CustomerLicenseActivation
    {
        public int LicenceActID { get; set; }
        public int CustomerID { get; set; }
        public int PlanID { get; set; }
        public int ActivationCount { get; set; }
        public DateTime ActivationDate { get; set; }
        public DateTime LastActivationDate { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public int? UpdatedBy { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Plan Plan { get; set; }
    }
}